### PR TITLE
Fix validator details

### LINKED ISSUE #603: "Blue" screen on validator details
if validator does not contain beacon node, `ValidatorStats.tsx` fails to read data and throw an error
> image

>  image

### PR DESCRIPTION
**Pull request by BeroBurny**
### PR Checklist

- [x] I have run type check locally
- [x] I have run linter locally
- [ ] I have run unit and integration tests locally
- [x] Rebased to master branch / merged master

### Changes

- fix blue screen
### Issues

Closes #603

### CODE REVIEW

**Review by mpetrunic — DISMISSED** [review]

File: src/renderer/containers/ValidatorDetails/ValidatorStats/ValidatorStats.tsx [hunk 1]
```diff
@@ -104,8 +104,8 @@ export const ValidatorStats = ({validator}: IValidatorStatsProps): ReactElement
                 <ValidatorAttestationEfficiencyChart data={attestationData} />
             </div>
             <div className='beacon-node-charts-container'>
-                <ValidatorAttestationsTable publicKey={validator.publicKey} slot={beaconNode.slot} />
-                <ValidatorPropositionsTable publicKey={validator.publicKey} slot={beaconNode.slot} />
+                <ValidatorAttestationsTable publicKey={validator.publicKey} slot={beaconNode?.slot || 0} />
+                <ValidatorPropositionsTable publicKey={validator.publicKey} slot={beaconNode?.slot || 0} />
```
Comment (mpetrunic) [inline src/renderer/containers/ValidatorDetails/ValidatorStats/ValidatorStats.tsx]: maybe better not to hardcode it but to import GENESIS_SLOT from some package

**Review by mpetrunic — COMMENTED** [review]
CI failling

**Review by mpetrunic — APPROVED** [review]
