### PR TITLE
fix feedback on beacon node not found

### LINKED ISSUE #371: Add feedback on wrong link on "add beacon"
Display error if beacon response code is not ok (200)

### PR DESCRIPTION
**Pull request by BeroBurny**
fixes #371

### CODE REVIEW

File: src/renderer/services/eth2/client/index.ts [hunk 1]
```diff
@@ -26,10 +26,6 @@ export function getEth2ApiClient(url: string, network: string, logger?: ILogger)
 export async function readBeaconChainNetwork(url: string): Promise<INetworkConfig | null> {
     // eslint-disable-next-line camelcase
     type GenesisRequestType = {data: {genesis_fork_version: string}};
```
Comment (mpetrunic) [inline src/renderer/services/eth2/client/index.ts:28]: Just saw this. This is typo, it's GenesisResponseType

**Review by mpetrunic — APPROVED** [review]
