### PR TITLE
Fix validator and beacon logs

### LINKED ISSUE #412: Error messages not visible in validator logs
```
2021-01-10 10:54:37 [] [31merror[39m: Failed to obtain attester duty epoch=11832, error=[object Object]
2021-01-10 10:54:37 [] [31merror[39m: Failed to obtain proposer duties message=[object Object]
```

https://pastebin.com/4Xutcu1X

### LINKED ISSUE #419: Log file doesn't contain serialized error message
```
[2021-01-11 12:53:43.301] [error] Failed to fetch validator {
  validatorId: '0x96cc7cd9a433cdbfe0cb845aa297fae1000fc2a281fcf2c94d367e46e9e15cecee3e664c48ef50036cbc5d402c7f1967',
  error: '[object Object]'
}
```

### PR DESCRIPTION
**Pull request by BeroBurny**
closes #412 
closes #419

### CODE REVIEW

File: src/renderer/services/eth2/client/eth2ApiClient/cgEth2BeaconStateApi.ts [hunk 1]
```diff
@@ -32,8 +32,7 @@ export class CgEth2BeaconStateApi implements ICGBeaconStateApi {
             }>(url);
             return BigInt(finalityCheckpointsResponse.data.previous_justified.epoch);
         } catch (e) {
-            // TODO: implement logger;
```
Comment (mpetrunic) [inline src/renderer/services/eth2/client/eth2ApiClient/cgEth2BeaconStateApi.ts:35]: electron log?

**Review by mpetrunic — APPROVED** [review]
