### PR TITLE
Beacon node slot height

### LINKED ISSUE #359: Slot height not working
implement and use getSyncingStatus - https://ethereum.github.io/eth2.0-APIs/#/Node/getSyncingStatus
rename `slot height` to `head slot`

### PR DESCRIPTION
**Pull request by BeroBurny**
closes #359

### CODE REVIEW

File: src/renderer/ducks/beacon/sagas.ts [hunk 1]
```diff
@@ -90,20 +113,23 @@ function* initializeBeaconsFromStore(): Generator<
             beacons.map(({url}) =>
                 new HttpClient(url)
                     // eslint-disable-next-line camelcase
-                    .get<{data: {is_syncing: boolean}}>("/eth/v1/node/syncing")
-                    .then((response) => response.data.is_syncing)
+                    .get<{data: {is_syncing: boolean; head_slot: number}}>("/eth/v1/node/syncing")
```
Comment (mpetrunic) [inline src/renderer/ducks/beacon/sagas.ts:116]: Can we extract this to some method. Or even better to use eth2Client.

File: src/renderer/ducks/beacon/sagas.ts [hunk 2]
```diff
@@ -113,6 +139,56 @@ function* initializeBeaconsFromStore(): Generator<
...
+    | Promise<INetworkConfig | null>,
+    void,
+    EventChannel<HeadEvent | FinalizedCheckpointEvent> &
+        (HeadEvent | FinalizedCheckpointEvent) &
+        [HeadEvent | FinalizedCheckpointEvent, ReturnType<typeof removeBeacon>] &
+        (INetworkConfig | null)
+> {
+    const config = yield readBeaconChainNetwork(url);
+    const client = new CgEth2ApiClient(config?.eth2Config || mainnetConfig, url);
+    const emitter = client.events.getEventStream([
```
Comment (mpetrunic) [inline src/renderer/ducks/beacon/sagas.ts:159]:
```suggestion
    const eventStream = client.events.getEventStream([
```

File: src/renderer/ducks/beacon/sagas.ts [hunk 3]
```diff
@@ -113,6 +139,56 @@ function* initializeBeaconsFromStore(): Generator<
...
+        BeaconEventType.HEAD,
+        (CGBeaconEventType.FINALIZED_CHECKPOINT as unknown) as BeaconEventType,
```
Comment (mpetrunic) [inline src/renderer/ducks/beacon/sagas.ts:161]: add comment referencing lodestar code

File: src/renderer/ducks/beacon/sagas.ts [hunk 4]
```diff
@@ -113,6 +139,56 @@ function* initializeBeaconsFromStore(): Generator<
...
+                if (cancelAction.payload === url) {
+                    yield cancel();
+                }
+                continue;
+            }
+            if (payload.type === BeaconEventType.HEAD) yield put(updateSlot(payload.message.slot, url));
+            if (payload.type === CGBeaconEventType.FINALIZED_CHECKPOINT)
+                yield put(finalizedEpoch(url, payload.message.epoch));
+        } catch (err) {
+            console.error("Event error:", err.message);
```
Comment (mpetrunic) [inline src/renderer/ducks/beacon/sagas.ts:187]: no console

**Review by mpetrunic — APPROVED** [review]
