### PR TITLE
Fix add validator flow

### LINKED ISSUE #155: Add new validator contains only signing key
Current flow:

1. ADd new validator
2. Import/Generate signing key
3. Enter password
4. Modal closed

Should go to withdrawal key and deposit...

### PR DESCRIPTION
**Pull request by morrigan**
Resolves #155 

Now adding new validator button leads through whole onboarding process, checking password (to create new keystores) and redirecting to dashboard. 

I have added new property in CGDatabase which is number of validators. The reason for this is that I can't trigger `useEffect` for loading validators and rerender with new validators list because `validators` is private. I am open to other ideas... Maybe the best would be not to store CGAccount as model in Redux store.

### CODE REVIEW

File: src/renderer/actions/register.ts [hunk 1]
```diff
@@ -103,19 +104,26 @@ export interface IWithdrawalKeyAction extends Action<RegisterActionTypes> {
     payload: IStoreWithdrawalKeyPayload;
 }
 
+const saveKeystore = async(state: IRootState, password: string): Promise<string> => {
+    const signingKey = PrivateKey.fromBytes(
+        Buffer.from(state.register.signingKey.replace("0x",""), "hex")
```
Comment (mpetrunic) [inline src/renderer/actions/register.ts]: I think there is method stringToBuffer or something like that in our codebase

File: test/e2e/redux/reducers/register.reducer.spec.ts [hunk 2]
```diff
@@ -24,6 +24,7 @@ const initalState: IRegisterState = {
     withdrawalVerification: false,
     withdrawalKey: "",
     network: SupportedNetworks.PRYSM,
+    addingNewValidator: false,
```
Comment (mpetrunic) [inline test/e2e/redux/reducers/register.reducer.spec.ts]: i would prefer type: [REGISTER, ADD] instead of flags

File: src/renderer/containers/Dashboard/DashboardContainer.tsx [hunk 3]
```diff
@@ -127,7 +116,7 @@ const Dashboard: React.FunctionComponent<IOwnProps & IInjectedProps & Pick<IRoot
         }
 
         loadValidators();
-    },[]);
+    },[props.auth.account && props.auth.account.numberOfValidators]);
```
Comment (mpetrunic) [inline src/renderer/containers/Dashboard/DashboardContainer.tsx]: Cant you do here just `props.auth.account && props.auth.account.validators.length`?

File: src/renderer/models/account.ts [hunk 4]
```diff
@@ -118,13 +120,16 @@ export class CGAccount implements IAccount {
                 this.validators.push(validator);
             }
         }
+        this.numberOfValidators = this.validators.length;
     }
 
     public addValidator(validator: Keypair): void {
         this.validators.push(validator);
+        this.numberOfValidators++;
```
Comment (mpetrunic) [inline src/renderer/models/account.ts]: I think render will trigger if you set here `this.validators = this.validators.concat(validator)` as it's gonna create new array

File: src/renderer/containers/Dashboard/DashboardContainer.tsx (hunk 3 above)
Comment (morrigan) [reply src/renderer/containers/Dashboard/DashboardContainer.tsx]: Nop, can't access validators

Comment (mpetrunic) [reply src/renderer/containers/Dashboard/DashboardContainer.tsx]: props.auth.account.getValidators().length? :)

Comment (morrigan) [reply src/renderer/containers/Dashboard/DashboardContainer.tsx]: lol, that actually works xD

File: src/renderer/actions/network.ts [hunk 5]
```diff
@@ -50,9 +51,7 @@ export const saveSelectedNetworkAction = (network: string): ISaveSelectedNetwork
 export const saveBeaconNodeAction = (url: string, network?: string) => {
     return async (dispatch: Dispatch<Action<unknown>>, getState: () => IRootState): Promise<void> => {
         const localDockerName = network ? BeaconChain.getContainerName(network) : undefined;
-        const signingKey = PrivateKey.fromBytes(
-            Buffer.from(getState().register.signingKey.replace("0x",""), "hex")
-        );
+        const signingKey = PrivateKey.fromBytes(fromHex(getState().register.signingKey.replace("0x","")));
```
Comment (mpetrunic) [inline src/renderer/actions/network.ts]: isn't from hex already removing 0x?

Comment (morrigan) [reply src/renderer/actions/network.ts]: No, that's just to create Buffer from string. We don't have much usage of this currently

Comment (mpetrunic) [reply src/renderer/actions/network.ts]: Can you add 0x removal there so we don't copy code everywhere
