### PR TITLE
Fix beacon node delete then add

### LINKED ISSUE #376: local beacon node "recreate"
After creating local beacon node deleting it and then creating new one will not start new local docker image

### PR DESCRIPTION
**Pull request by BeroBurny**
closes #376

### CODE REVIEW

File: src/renderer/ducks/beacon/sagas.ts [hunk 1]
```diff
@@ -92,8 +108,22 @@ function* storeBeacon({payload: {url, docker}}: ReturnType<typeof addBeacon>): G
...
+    SelectEffect | PutEffect | Promise<[boolean, boolean]> | Promise<ValidatorBeaconNodes>,
+    void,
+    [boolean, boolean] & BeaconValidators & ValidatorBeaconNodes
+> {
+    const [removed] = yield database.beacons.remove(payload);
+    if (removed) {
+        const beaconValidators = yield select(getValidatorsByBeaconNode);
+        for (const {publicKey} of beaconValidators[payload]) {
+            const {nodes} = yield database.validatorBeaconNodes.remove(publicKey, payload);
+            console.log(nodes, payload);
```
Comment (mpetrunic) [inline src/renderer/ducks/beacon/sagas.ts:123]: khm

**Review by mpetrunic — APPROVED** [review]
