### PR TITLE
Fix beacon node requests and listening

### LINKED ISSUE #256: Unsubscribe from onNewChainHead when node is removed

### LINKED ISSUE #259: Duplicated beacon node load requests
Screenshot 2020-06-16 at 11 56 45

### PR DESCRIPTION
**Pull request by morrigan**
- Closes #259
- Closes #256

### CODE REVIEW

File: src/renderer/actions/validator.ts [hunk 1]
```diff
@@ -49,19 +50,69 @@ export const loadValidatorsAction = () => {
...
 
+export interface IAddValidator {
+    type: typeof ValidatorActionTypes.LOAD_VALIDATORS,
+    payload: IValidator,
+}
+
+export const addNewValidator = (publicKey: string) => {
+    return async (dispatch: Dispatch<Action<unknown>>, getState: () => IRootState): Promise<void> => {
+        const keystore = getState().auth.account.loadKeystore(publicKey);
+        const validator = {
```
Comment (mpetrunic) [inline src/renderer/actions/validator.ts:65]: no type?

File: src/renderer/actions/validator.ts [hunk 2]
```diff
@@ -49,19 +50,69 @@ export const loadValidatorsAction = () => {
...
+            type: ValidatorActionTypes.ADD_VALIDATOR,
+            payload: validator,
+        });
+    };
+};
+
+export interface IRemoveValidator {
+    type: typeof ValidatorActionTypes.LOAD_VALIDATORS,
+    payload: {
+        validator: string,
```
Comment (mpetrunic) [inline src/renderer/actions/validator.ts:82]: validatorPublicKey?
