### PR TITLE
Fix add remote beacon error's

### LINKED ISSUE #457: No error message on unreachable beacon node
To replicate: 

1. Trying to connect to: `http://eth2.office.nodefactory.io:5052`
2. Response is probably not found or so as I am not connected to our WiFi network
3. "Go clicked" multiple times, no error message is displayed or any change

### PR DESCRIPTION
**Pull request by BeroBurny**
closes #457

### CODE REVIEW

File: src/renderer/components/ConfigureBeaconNode/InputBeaconNode.tsx [hunk 1]
```diff
@@ -31,7 +32,12 @@ export const InputBeaconNode: React.FunctionComponent<IInputBeaconNodeProps> = (
         }
 
         try {
-            const network = await readBeaconChainNetwork(beaconNodeInput);
+            // eslint-disable-next-line camelcase
+            const response = await axios.get<{data: {genesis_fork_version: string}}>(`/eth/v1/beacon/genesis`, {
```
Comment (mpetrunic) [inline src/renderer/components/ConfigureBeaconNode/InputBeaconNode.tsx:36]: we should at least move this to some static method on cgeth2client?

Comment (mpetrunic) [reply src/renderer/components/ConfigureBeaconNode/InputBeaconNode.tsx:36]: Yeah but it would be quite difficult to find this line of code in case response or url changes

**Review by mpetrunic — APPROVED** [review]
