### PR TITLE
Fix atterstation effectivnes

### LINKED ISSUE #485: Reorganize validator and beacon node tabs
When beacon node is clicked, only beacon node information should be displayed:

 * beacon node details  - "Dashboard"
 * beacon node logs - "Logs"
 * performance - "Performance"

Remove beacon node from validator details.

### PR DESCRIPTION
**Pull request by BeroBurny**
closes #485

### CODE REVIEW

File: src/renderer/ducks/validator/actions.ts [hunk 1]
```diff
@@ -83,14 +83,15 @@ export type SignedNewAttestation = (
...
-    payload: {block: string; index: number; slot: number};
+    payload: {block: string; index: number; slot: number; bits: string};
     meta: string;
 };
 export const signedNewAttestation = createAction<SignedNewAttestation>(
     "validator/signedNewAttestation",
-    (publicKey: string, block: string, index: number, slot: number) => ({
-        payload: {block, index, slot},
+    (publicKey: string, block: string, index: number, slot: number, bits: string) => ({
+        payload: {block, index, slot, bits},
```
Comment (mpetrunic) [inline src/renderer/ducks/validator/actions.ts:94]: you don't need bits here. YOu just need index of true bit in attestation (new attestation must have only 1 bit set - on index matching validator position in committee).

File: src/renderer/ducks/validator/sagas.ts [hunk 2]
```diff
@@ -445,17 +446,19 @@ export function* getAttestationEffectiveness({
                 skippedQue++;
             } else {
                 const sanitizedAttestations = result.filter(
-                    ({data}) => payload.block === toHex(data.beaconBlockRoot) && data.index === payload.index,
+                    ({data, aggregationBits}) =>
+                        payload.block === toHex(data.beaconBlockRoot) &&
+                        data.index === payload.index &&
+                        data.slot === payload.slot &&
+                        payload.bits === JSON.stringify(aggregationBits),
```
Comment (mpetrunic) [inline src/renderer/ducks/validator/sagas.ts:453]: You need to check if bit on validator position in committee is set to true. I think you should also check source and target root.

**Review by mpetrunic — CHANGES_REQUESTED** [review]

File: src/renderer/ducks/validator/sagas.ts (hunk 2 above)
Comment (BeroBurny) [reply src/renderer/ducks/validator/sagas.ts:453]: `source` and `target` contains `epoch` and `root` of `slot` as i check `source` `slot` in parent object of `source` and think checking for `source` and `target` can be bit a overkill and add unnecessary complexity

Comment (mpetrunic) [reply src/renderer/ducks/validator/sagas.ts]: it contains epoch and epoch boundary root (it's basically validator vote) that are unreleated to slot. That said since, you are checking committee index, it's highly unlikely that someone created attestation with different source and target outside of chainguardian (in that case more pressing issue is slashing anyways).

File: src/renderer/ducks/validator/actions.ts [hunk 3]
```diff
@@ -83,14 +83,15 @@ export type SignedNewAttestation = (
     block: string,
     index: number,
     slot: number,
+    bitsIndex: number,
 ) => {
-    payload: {block: string; index: number; slot: number};
+    payload: {block: string; index: number; slot: number; bitsIndex: number};
```
Comment (mpetrunic) [inline src/renderer/ducks/validator/actions.ts:88]:
```suggestion
    payload: {block: string; index: number; slot: number; validatorIndexInCommittee: number};
```

File: src/renderer/ducks/validator/sagas.ts [hunk 4]
```diff
@@ -445,30 +445,31 @@ export function* getAttestationEffectiveness({
                 skippedQue++;
             } else {
                 const sanitizedAttestations = result.filter(
-                    ({data}) => payload.block === toHex(data.beaconBlockRoot) && data.index === payload.index,
+                    ({data, aggregationBits}) =>
+                        payload.block === toHex(data.beaconBlockRoot) &&
+                        data.index === payload.index &&
+                        data.slot === payload.slot &&
+                        payload.bitsIndex === aggregationBits.findIndex((bit) => bit),
```
Comment (mpetrunic) [inline src/renderer/ducks/validator/sagas.ts:452]:
```suggestion
                        aggregationBits[validatorIndexInCommittee] === true
```

File: src/renderer/services/eth2/client/eth2ApiClient/cgEth2BeaconPoolApi.ts [hunk 5]
```diff
@@ -24,6 +24,7 @@ export class CgEth2BeaconPoolApi implements IBeaconPoolApi {
                     toHex(attestation.data.beaconBlockRoot),
                     attestation.data.index,
                     attestation.data.slot,
+                    attestation.aggregationBits.findIndex((bit) => Number(bit) === -1),
```
Comment (mpetrunic) [inline src/renderer/services/eth2/client/eth2ApiClient/cgEth2BeaconPoolApi.ts:27]:
```suggestion
                    attestation.aggregationBits.findIndex((bit) => bit === true),
```

File: src/renderer/ducks/validator/actions.ts (hunk 3 above)
Comment (mpetrunic) [reply src/renderer/ducks/validator/actions.ts:88]: you should maybe throw error if this is < 0 (Don't think it can happen but to be on the safe side)

Comment (BeroBurny) [reply src/renderer/ducks/validator/actions.ts:88]: how we should handle this error if happens?

File: src/renderer/services/eth2/client/eth2ApiClient/cgEth2BeaconPoolApi.ts (hunk 5 above)
Comment (BeroBurny) [reply src/renderer/services/eth2/client/eth2ApiClient/cgEth2BeaconPoolApi.ts:27]: we talk about this... for some reason we got `-true` what is `-1`, if i try to compare `bit === -true` got type error i cannot compare boolean with number

File: src/renderer/ducks/validator/actions.ts (hunk 3 above)
Comment (BeroBurny) [reply src/renderer/ducks/validator/actions.ts:88]: i can add case if is index `-1` (not found) to not call saga

File: src/renderer/services/eth2/client/eth2ApiClient/cgEth2BeaconPoolApi.ts (hunk 5 above)
Comment (mpetrunic) [reply src/renderer/services/eth2/client/eth2ApiClient/cgEth2BeaconPoolApi.ts:27]: I don't think that's possible could you log aggregation bits and post logs here?

**Review by mpetrunic — APPROVED** [review]
