### PR TITLE
Fix copy button memory leak and tooltip

### LINKED ISSUE #163: Copy Button - memory leak
- Can't perform a React state update on an unmounted component.

### PR DESCRIPTION
**Pull request by mpetrunic**
resolves #163

### CODE REVIEW

File: src/renderer/components/Button/ButtonAction.tsx [hunk 1]
```diff
@@ -13,48 +14,62 @@ export interface ICopyButtonProps {
...
 
-    return(<button
-        className={"copy-button"} 
+    useEffect(() => {
+        return function cleanup(): void {
+            if (timeoutId) {
+                window.clearTimeout(timeoutId);
+            }
+        };
+    });
```
Comment (morrigan) [inline src/renderer/components/Button/ButtonAction.tsx]: You should memoize `timeoutId`. Also, I don't think you need to return a function...
